trigger:
  - main

jobs:
  - job: Build
    displayName: 'Build Job'
    pool:
      name: 'SelfHostedAgents'  # Use your custom pool name

    steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '6.0.300'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - script: echo Hello, world!
        displayName: 'Run a one-line script'
