trigger:
  - main  # The branch that will trigger the pipeline

# Use the self-hosted agent pool
pool:
  name: 'SelfHostedAgents'  # Replace with your self-hosted agent pool name

steps:
  # Run a simple echo command
  - script: echo "Hello, World!"
    displayName: 'Echo Hello World'
