trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.300'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: echo Hello, world!
    displayName: 'Run a one-line script'
